### ISSUE TITLE
Consider this similar project:

### ISSUE THREAD

**Issue by RoneoOrg** [bowman2001/hugo-mod-material-symbols#1]
Hi there,

my Github feed told me about your project.
I had a similar need and coded this: https://github.com/RoneoOrg/hugo-shortcode-roneo-collection#use-inline-svg-icons

More details in this blog post: https://roneo.org/en/hugo-svg-icon-shortcode/

Material icons are not included yet but it's easy (and documented) to add more icon sets

Cheers

**Comment by bowman2001** [comment]
Hi, 

thanks for the hint! I'm going to look into your code again, because many steps are similar to acomplish this, you're right. The nice and also problematic thing about material SVG symbols (not icons) is: There are so many versions of them (in total a few gigs). I'm using different sets and need to extract them and allow my partial and shortcode to choose between these selected sets. Therefor, I need a few additional steps in this module.

See ya,
Georg
